"""
Excel export functionality for test cases.
"""

import io
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter


def generate_excel(test_cases, feature_name="Test_Cases"):
    """
    Generate an Excel file from test cases.
    
    Args:
        test_cases: List of test case dictionaries
        feature_name: Name of the feature (used for sheet title)
    
    Returns:
        BytesIO buffer containing the Excel file
    """
    # Create workbook
    wb = Workbook()
    ws = wb.active
    ws.title = "Test Cases"
    
    # Define styles
    header_font = Font(bold=True, color="FFFFFF", size=11)
    header_fill = PatternFill(start_color="3E3D6D", end_color="3E3D6D", fill_type="solid")
    header_alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
    
    cell_alignment = Alignment(vertical="top", wrap_text=True)
    cell_border = Border(
        left=Side(style='thin', color='E5E7EB'),
        right=Side(style='thin', color='E5E7EB'),
        top=Side(style='thin', color='E5E7EB'),
        bottom=Side(style='thin', color='E5E7EB')
    )
    
    # Add title row
    ws.merge_cells('A1:F1')
    title_cell = ws['A1']
    title_cell.value = f"Test Cases - {feature_name}"
    title_cell.font = Font(bold=True, size=14, color="3E3D6D")
    title_cell.alignment = Alignment(horizontal="center", vertical="center")
    ws.row_dimensions[1].height = 30
    
    # Add headers
    headers = ["ID", "Title", "Description", "Preconditions", "Test Steps", "Expected Result"]
    for col_num, header in enumerate(headers, 1):
        cell = ws.cell(row=2, column=col_num)
        cell.value = header
        cell.font = header_font
        cell.fill = header_fill
        cell.alignment = header_alignment
        cell.border = cell_border
    
    ws.row_dimensions[2].height = 25
    
    # Add test cases
    for row_num, tc in enumerate(test_cases, 3):
        # ID
        cell = ws.cell(row=row_num, column=1)
        cell.value = tc.get('id', f'TC_{row_num-2:03d}')
        cell.alignment = Alignment(horizontal="center", vertical="top")
        cell.border = cell_border
        cell.font = Font(bold=True)
        
        # Title
        cell = ws.cell(row=row_num, column=2)
        cell.value = tc.get('title', '')
        cell.alignment = cell_alignment
        cell.border = cell_border
        
        # Description
        cell = ws.cell(row=row_num, column=3)
        cell.value = tc.get('description', '')
        cell.alignment = cell_alignment
        cell.border = cell_border
        
        # Preconditions
        cell = ws.cell(row=row_num, column=4)
        cell.value = tc.get('preconditions', '')
        cell.alignment = cell_alignment
        cell.border = cell_border
        
        # Test Steps
        cell = ws.cell(row=row_num, column=5)
        steps = tc.get('steps', [])
        if isinstance(steps, list):
            cell.value = "\n".join(f"{i+1}. {step}" for i, step in enumerate(steps))
        else:
            cell.value = str(steps)
        cell.alignment = cell_alignment
        cell.border = cell_border
        
        # Expected Result
        cell = ws.cell(row=row_num, column=6)
        cell.value = tc.get('expected_result', '')
        cell.alignment = cell_alignment
        cell.border = cell_border
        
        # Set row height based on content
        ws.row_dimensions[row_num].height = max(40, min(100, len(str(tc)) // 3))
    
    # Set column widths
    ws.column_dimensions['A'].width = 12
    ws.column_dimensions['B'].width = 35
    ws.column_dimensions['C'].width = 40
    ws.column_dimensions['D'].width = 35
    ws.column_dimensions['E'].width = 50
    ws.column_dimensions['F'].width = 40
    
    # Add summary sheet
    summary_ws = wb.create_sheet("Summary")
    summary_ws['A1'] = "Test Case Summary"
    summary_ws['A1'].font = Font(bold=True, size=14, color="3E3D6D")
    
    summary_ws['A3'] = "Feature:"
    summary_ws['B3'] = feature_name
    summary_ws['A3'].font = Font(bold=True)
    
    summary_ws['A4'] = "Total Test Cases:"
    summary_ws['B4'] = len(test_cases)
    summary_ws['A4'].font = Font(bold=True)
    
    summary_ws['A6'] = "Generated By:"
    summary_ws['B6'] = "Agent TC Generator"
    
    summary_ws.column_dimensions['A'].width = 20
    summary_ws.column_dimensions['B'].width = 40
    
    # Save to buffer
    buffer = io.BytesIO()
    wb.save(buffer)
    buffer.seek(0)
    
    return buffer
